[package]
name = "move-started"
version = "0.0.0"

[dependencies]
MoveStdlib = { local = "./lib/move-stdlib" }
AptosStdlib = { local = "./lib/aptos-stdlib" }
AptosFramework = { local = "./lib/aptos-framework" }

[addresses]
std =  "0x1"
aptos_framework =  "0x1"
move_dao = "0xC0FFEE"
BlockSec = "0xC0FFEB"
